### ISSUE TITLE
Scheduled job for December AoC

### ISSUE THREAD

**Issue by Kavignon** [Kavignon/Elixir-journey#12]
# Description

Create a scheduled job that runs daily from December 1st to December 25th to automate the setup process for each day’s AoC challenge.

## Tasks

Referencing the work done during the scope of #10 

- [ ] Create a new GitHub issue for the day's problem.
- [ ] Create a new branch for each day’s problem. _Branch name should follow the pattern AoC_YYYY_dayXX_problem-title_.
- [ ] Pull the problem prompt for the given day and store it.
- [ ] Automate downloading the personalized input data for the given day.
- [ ] Generate boilerplate code for solving the day’s problem.
